version: "3.9"
services:
  backend:
    image: node:20.18-slim
    stdin_open: true
    tty: true
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app:cached
    command:
      - sh
      - -c
      - |
        npm i
        npm run start:dev
    ports:
      - "3000:3000"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

  frontend:
    image: node:18.18-slim
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
    command:
      - sh
      - -c
      - |
        npm i
        npm run dev
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #     - frontend
